### ISSUE TITLE
Server error when uploading new image file

### ISSUE THREAD

**Issue by dbrower** [ndlib/curate_nd#404]
This is from spiceworks ticket #11749.

I put the request parameter list seemed private, so is in the SW ticket. This looks to be the corresponding backtrace in the log file:

```
{"message":"Curate caught a registered error: ActiveFedora::UnknownAttributeError
\tunknown attribute: record_record_editors_attributes
\tBacktrace:
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/active-fedora-6.7.8/lib/active_fedora/attributes.rb:22:in `block in attributes='
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/active-fedora-6.7.8/lib/active_fedora/attributes.rb:21:in `each'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/active-fedora-6.7.8/lib/active_fedora/attributes.rb:21:in `attributes='
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/active-fedora-6.7.8/lib/active_fedora/attributes/serializers.rb:26:in `attributes='
\t/home/app/curatend/releases/20160427140416/app/services/curation_concern/base_actor.rb:74:in `apply_save_data_to_curation_concern'
\t/home/app/curatend/releases/20160427140416/app/services/curation_concern/base_actor.rb:24:in `create'
\t/home/app/curatend/releases/20160427140416/app/services/curation_concern/generic_work_actor.rb:10:in `create'
\t/home/app/curatend/releases/20160427140416/app/controllers/curation_concern/generic_works_controller.rb:13:in `create'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:189:in `process_action'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/rendering.rb:10:in `process_action'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:503:in `_run__2049466494268609122__process_action__callbacks'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:17:in `process_action'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/rescue.rb:29:in `process_action'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.13/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:136:in `process'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:44:in `process'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:195:in `dispatch'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:231:in `block in action'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:50:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:71:in `block in call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `each'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:676:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/rack/error_collector.rb:50:in `traced_call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/rack/agent_hooks.rb:26:in `traced_call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/devise_cas_authenticatable-1.3.2/lib/devise_cas_authenticatable/single_sign_out/rack.rb:11:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/breach-mitigation-rails-0.2.2/lib/breach_mitigation/length_hiding.rb:10:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/conditionalget.rb:35:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/head.rb:11:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/flash.rb:241:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/cookies.rb:486:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.13/lib/active_record/query_cache.rb:36:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.9.5.251/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:29:in `block in
[truncated]
```

**Comment by danhorst** [comment]
I was able to reproduce this error by adding a second contributor to an existing record before saving.

**Comment by ruthtillman** [comment]
I was definitely having this issue on libvirt8. Do not recall if I had on Curate.

**Comment by danhorst** [comment]
The problem was introduced here: 0462056c593f187fadb6a0c4a52387d04e06f1e4

Specifically, this view was altered incorrectly yeilding `record_record_editor` instead of `record_editor`: https://github.com/ndlib/curate_nd/blob/0462056c593f187fadb6a0c4a52387d04e06f1e4/app/views/curation_concern/base/_linked_record_editors.html.erb
