### ISSUE TITLE
Show page error when rendering a collection

### ISSUE THREAD

**Issue by danhorst** [ndlib/curate_nd#503]
Found by @ruthtillman 

Record in question:
https://curatepprd.library.nd.edu/show/dev00137f48

Error log:
```
{"method":"GET","path":"/show/dev00137f48","format":"html","controller":"common_objects","action":"show","status":500,"duration":916.06,"view":8.71,"db":3.68,"params":{"id":"dev00137f48"},"@timestamp":"2016-08-15T15:40:19.125-04:00","@version":"1","message":"[500] GET /show/dev00137f48 (common_objects#show)","severity":"INFO","host":"curatesvrpprd.library.nd.edu"}
{"message":"Curate caught a registered error: TypeError\n\twrong argument type Collection (expected String)\n\tBacktrace:\n\t/home/app/curatend/releases/20160815181543/lib/curate/text_formatter.rb:14:in `render'\n\t/home/app/curatend/releases/20160815181543/lib/curate/text_formatter.rb:14:in `call'\n\t/home/app/curatend/releases/20160815181543/app/helpers/curate_helper.rb:241:in `richly_formatted_text'\n\t/home/app/curatend/releases/20160815181543/app/helpers/curate_helper.rb:101:in `__render_tabular_list_item'\n\t/home/app/curatend/releases/20160815181543/app/helpers/curate_helper.rb:92:in `block in render_collection_as_tabular_list'\n\t/home/app/curatend/releases/20160815181543/app/helpers/curate_helper.rb:88:in `each'\n\t/home/app/curatend/releases/20160815181543/app/helpers/curate_helper.rb:88:in `render_collection_as_tabular_list'\n\t/home/app/curatend/releases/20160815181543/app/helpers/curate_helper.rb:68:in `curation_concern_attribute_to_html'\n\t/home/app/curatend/releases/20160815181543/app/views/curation_concern/images/_attributes.html.erb:23:in `_app_views_curation_concern_images__attributes_html_erb___2448139405367387772_70201797508140'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/template.rb:143:in `block in render'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:161:in `instrument'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/template.rb:141:in `render'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/partial_renderer.rb:279:in `block in render'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:161:in `instrument'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/partial_renderer.rb:278:in `render'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/renderer.rb:47:in `render_partial'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/helpers/rendering_helper.rb:27:in `render'\n\t/home/app/curatend/releases/20160815181543/app/views/common_objects/show.html.erb:31:in `block in _app_views_common_objects_show_html_erb__487115101364551499_70201810174540'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/helpers/capture_helper.rb:38:in `capture'\n\t/home/app/curatend/releases/20160815181543/app/views/common_objects/show.html.erb:29:in `_app_views_common_objects_show_html_erb__487115101364551499_70201810174540'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/template.rb:143:in `block in render'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:161:in `instrument'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/template.rb:141:in `render'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:49:in `block (2 levels) in render_template'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:161:in `instrument'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:48:in `block in render_template'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:56:in `render_with_layout'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:47:in `render_template'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/template_renderer.rb:17:in `render'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/renderer.rb:42:in `render_template'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_view/renderer/renderer.rb:23:in `render'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:127:in `_render_template'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/streaming.rb:219:in `_render_template'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:120:in `render_to_body'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/rendering.rb:33:in `render_to_body'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/renderers.rb:26:in `render_to_body'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:97:in `render'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/rendering.rb:16:in `render'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'\n\t/opt/ruby/2.0.0-p353/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/core_ext/benchmark.rb:12:in `ms'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:41:in `block in render'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.13/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:40:in `render'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/implicit_render.rb:10:in `default_render'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/responder.rb:233:in `default_render'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/responder.rb:161:in `to_html'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/responder.rb:154:in `respond'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/responder.rb:147:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/mime_responds.rb:330:in `respond_with'\n\t/home/app/curatend/releases/20160815181543/app/controllers/common_objects_controller.rb:29:in `show'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/implicit_render.rb:4:in `send_action'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:189:in `process_action'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/rendering.rb:10:in `process_action'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:18:in `block in process_action'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:463:in `_run__451429775802802244__process_action__callbacks'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:17:in `process_action'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/rescue.rb:29:in `process_action'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:30:in `process_action'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.13/lib/active_record/railties/controller_runtime.rb:18:in `process_action'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:136:in `process'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:44:in `process'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:195:in `dispatch'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:231:in `block in action'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:50:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:71:in `block in call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `each'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:676:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/devise_cas_authenticatable-1.3.2/lib/devise_cas_authenticatable/single_sign_out/rack.rb:11:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/etag.rb:23:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/breach-mitigation-rails-0.2.2/lib/breach_mitigation/length_hiding.rb:10:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/conditionalget.rb:25:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/head.rb:11:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/params_parser.rb:27:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/flash.rb:241:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:225:in `context'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/session/abstract/id.rb:220:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/cookies.rb:486:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.13/lib/active_record/query_cache.rb:36:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:373:in `_run__3842744424699522844__call__callbacks'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:27:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/airbrake-4.3.8/lib/airbrake/rails/middleware.rb:13:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/lograge-0.3.5/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:20:in `block in call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/logstash-logger-0.15.2/lib/logstash-logger/tagged_logging.rb:5:in `block in tagged'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/logstash-logger-0.15.2/lib/logstash-logger/tagged_logging.rb:16:in `tagged'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/logstash-logger-0.15.2/lib/logstash-logger/tagged_logging.rb:5:in `tagged'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:20:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/request_id.rb:21:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/methodoverride.rb:21:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/runtime.rb:17:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/cache/strategy/local_cache.rb:83:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/sendfile.rb:112:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/airbrake-4.3.8/lib/airbrake/user_informer.rb:16:in `_call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/airbrake-4.3.8/lib/airbrake/user_informer.rb:12:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/railties-4.0.13/lib/rails/engine.rb:511:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/railties-4.0.13/lib/rails/application.rb:97:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/commonlogger.rb:33:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/chunked.rb:43:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/content_length.rb:14:in `call'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:552:in `process_client'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:632:in `worker_loop'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:500:in `spawn_missing_workers'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:511:in `maintain_worker_count'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:277:in `join'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/gems/unicorn-4.6.3/bin/unicorn:126:in `\u003Ctop (required)\u003E'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/bin/unicorn:23:in `load'\n\t/home/app/curatend/shared/bundle/ruby/2.0.0/bin/unicorn:23:in `\u003Cmain\u003E'\n\n\tRendering error page: 500","@timestamp":"2016-08-15T15:40:19.876-04:00","@version":"1","severity":"ERROR","host":"curatesvrpprd.library.nd.edu"}
```

**Comment by danhorst** [comment]
Closed via #507
