### ISSUE TITLE
Running seeds throws error trying to add files to work

### ISSUE THREAD

**Issue by laritakr** [ndlib/curate_nd#730]
```
rake aborted!
NoMethodError: undefined method `original_filename' for "class MockFile < Rack::Test::UploadedFile\n":String
/Users/lrobins5/git/curate_nd/app/services/curation_concern/generic_file_actor.rb:49:in `attach_file'
/Users/lrobins5/git/curate_nd/app/services/curation_concern/generic_file_actor.rb:9:in `block in create'
/Users/lrobins5/git/curate_nd/app/services/curation_concern/generic_file_actor.rb:7:in `each'
/Users/lrobins5/git/curate_nd/app/services/curation_concern/generic_file_actor.rb:7:in `create'
/Users/lrobins5/git/curate_nd/db/seeds/dev.rb:37:in `find_or_create'
/Users/lrobins5/git/curate_nd/db/seeds/dev.rb:130:in `block in <top (required)>'
/Users/lrobins5/git/curate_nd/db/seeds/dev.rb:127:in `times'
/Users/lrobins5/git/curate_nd/db/seeds/dev.rb:127:in `<top (required)>'
/Users/lrobins5/git/curate_nd/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:223:in `load'
/Users/lrobins5/git/curate_nd/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:223:in `block in load'
/Users/lrobins5/git/curate_nd/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
/Users/lrobins5/git/curate_nd/vendor/bundle/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:223:in `load'
/Users/lrobins5/git/curate_nd/lib/tasks/custom_seed.rake:8:in `block (4 levels) in <top (required)>'
/Users/lrobins5/git/curate_nd/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/lrobins5/.rbenv/versions/2.1.10/bin/bundle:23:in `load'
/Users/lrobins5/.rbenv/versions/2.1.10/bin/bundle:23:in `<main>'
Tasks: TOP => db:seed:dev
```

**Comment by laritakr** [comment]
Closed via https://github.com/ndlib/curate_nd/pull/737
